public class DreamWorld {
    public static Integer myValue = 0;  //Class Member variable
   public static String myString = ''; //Class Member variable
   
   public static Integer getCalculatedValue () {
   // Method definition and body
   // do some calculation
      myValue = myValue+10;
      return myValue;
   }
   public static void settest(){
        Set<String> Tech = new Set<String> {'Disney','Marvel','DC'};
        system.debug('Default DreamWorld List : '+Tech);
   }
}